
package tut02.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.5.5
 * Mon Mar 20 16:49:17 CET 2023
 * Generated source version: 3.5.5
 */

@XmlRootElement(name = "regReqResponse", namespace = "http://tut02/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "regReqResponse", namespace = "http://tut02/")

public class RegReqResponse {

    @XmlElement(name = "return")
    private java.lang.String _return;

    public java.lang.String getReturn() {
        return this._return;
    }

    public void setReturn(java.lang.String new_return)  {
        this._return = new_return;
    }

}

